name: app
version: 1.0.0+1
publish_to: none
description: demo app
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  universal_html: ^2.0.7
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  filesystem_picker: ^2.0.0-nullsafety.0
  flutter: 
    sdk: flutter
  file_picker: 
    path: /Users/ericm/sunny/local_plugins/flutter_file_picker
  flutter_quill: 
    path: /Users/ericm/sunny/local_plugins/flutter-quill
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/
  uses-material-design: true
