name: flutter_quill
version: 4.0.11
homepage: https://bulletjournal.us/home/index.html
description: A rich text editor supporting mobile and web (Demo App @ bulletjournal.us)
repository: https://github.com/singerdmx/flutter-quill
environment: 
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.10.0'
dependencies: 
  collection: ^1.16.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.3.0
  image_picker: ^0.8.2
  photo_view: ^0.14.0
  quiver: ^3.0.1+1
  string_validator: ^0.3.0
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  pedantic: ^1.11.1
  video_player: ^2.4.6
  characters: ^1.1.0
  youtube_player_flutter: ^8.0.0
  diff_match_patch: ^0.4.1
  i18n_extension: ^5.0.0
  gallery_saver: ^2.3.2
  device_info_plus: ^4.1.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
